stages:
- run_cv
- check_cv
.execute_cv_template:
  stage: run_cv
  tags:
  - tseethon-apptainer
  variables:
    GIT_STRATEGY: clone
  script:
  - export CMSSW_release=$CMSSW_release
  - export CRABClient_version=prod
  - export CRABServer_tag=HEAD
  - export REST_Instance=test12
  - export Client_Validation_Suite=true
  - export Repo_GH_Issue=novicecpp/CRABServer
  - export Repo_Testing_Scripts=novicecpp/CRABServer
  - export Branch_Testing_Scripts=wmcore_pypi
  - export Test_Docker_Image=registry.cern.ch/cmscrab/crabtesting:231009
  - bash -x cicd/gitlab/execute_test.sh
  cache:
  - key: $CI_PIPELINE_ID_$CMSSW_release
    paths:
    - artifacts/submitted_tasks_CV_$CMSSW_release
    policy: push
.check_cv_template:
  stage: check_cv
  tags:
  - tseethon-apptainer
  variables:
    GIT_STRATEGY: clone
  script:
  - export CMSSW_release=$CMSSW_release
  - export CRABClient_version=prod
  - export REST_Instance=test12
  - bash -x cicd/gitlab/check_clientValidation.sh
  cache:
  - key: $CI_PIPELINE_ID_$CMSSW_release
    paths:
    - artifacts/submitted_tasks_CV_$CMSSW_release
    policy: pull
.execute_cv:
  extends: .execute_cv_template
  variables:
    CMSSW_release: <placeholder>
.check_cv:
  extends: .check_cv_template
  variables:
    CMSSW_release: <placeholder>
    SCRAM_ARCH: <placeholder>
    singularity: <placeholder>
execute_cv_CMSSW_13_0_2:
  extends: .execute_cv_template
  variables:
    CMSSW_release: CMSSW_13_0_2
    SCRAM_ARCH: el8_amd64_gcc11
    singularity: '8'
check_cv_CMSSW_13_0_2:
  extends: .check_cv_template
  variables:
    CMSSW_release: CMSSW_13_0_2
    SCRAM_ARCH: el8_amd64_gcc11
    singularity: '8'
execute_cv_CMSSW_12_6_4:
  extends: .execute_cv_template
  variables:
    CMSSW_release: CMSSW_12_6_4
    SCRAM_ARCH: el8_amd64_gcc10
    singularity: '8'
check_cv_CMSSW_12_6_4:
  extends: .check_cv_template
  variables:
    CMSSW_release: CMSSW_12_6_4
    SCRAM_ARCH: el8_amd64_gcc10
    singularity: '8'
execute_cv_CMSSW_12_5_0:
  extends: .execute_cv_template
  variables:
    CMSSW_release: CMSSW_12_5_0
    SCRAM_ARCH: el8_amd64_gcc10
    singularity: '8'
check_cv_CMSSW_12_5_0:
  extends: .check_cv_template
  variables:
    CMSSW_release: CMSSW_12_5_0
    SCRAM_ARCH: el8_amd64_gcc10
    singularity: '8'
execute_cv_CMSSW_11_3_4:
  extends: .execute_cv_template
  variables:
    CMSSW_release: CMSSW_11_3_4
    SCRAM_ARCH: slc7_amd64_gcc900
    singularity: '7'
check_cv_CMSSW_11_3_4:
  extends: .check_cv_template
  variables:
    CMSSW_release: CMSSW_11_3_4
    SCRAM_ARCH: slc7_amd64_gcc900
    singularity: '7'
execute_cv_CMSSW_10_6_26:
  extends: .execute_cv_template
  variables:
    CMSSW_release: CMSSW_10_6_26
    SCRAM_ARCH: slc7_amd64_gcc700
    singularity: '7'
check_cv_CMSSW_10_6_26:
  extends: .check_cv_template
  variables:
    CMSSW_release: CMSSW_10_6_26
    SCRAM_ARCH: slc7_amd64_gcc700
    singularity: '7'
execute_cv_CMSSW_10_1_0:
  extends: .execute_cv_template
  variables:
    CMSSW_release: CMSSW_10_1_0
    SCRAM_ARCH: slc7_amd64_gcc630
    singularity: '7'
check_cv_CMSSW_10_1_0:
  extends: .check_cv_template
  variables:
    CMSSW_release: CMSSW_10_1_0
    SCRAM_ARCH: slc7_amd64_gcc630
    singularity: '7'
execute_cv_CMSSW_9_4_21:
  extends: .execute_cv_template
  variables:
    CMSSW_release: CMSSW_9_4_21
    SCRAM_ARCH: slc7_amd64_gcc630
    singularity: '7'
check_cv_CMSSW_9_4_21:
  extends: .check_cv_template
  variables:
    CMSSW_release: CMSSW_9_4_21
    SCRAM_ARCH: slc7_amd64_gcc630
    singularity: '7'
execute_cv_CMSSW_8_0_36:
  extends: .execute_cv_template
  variables:
    CMSSW_release: CMSSW_8_0_36
    SCRAM_ARCH: slc7_amd64_gcc530
    singularity: '7'
check_cv_CMSSW_8_0_36:
  extends: .check_cv_template
  variables:
    CMSSW_release: CMSSW_8_0_36
    SCRAM_ARCH: slc7_amd64_gcc530
    singularity: '7'
execute_cv_CMSSW_7_6_7:
  extends: .execute_cv_template
  variables:
    CMSSW_release: CMSSW_7_6_7
    SCRAM_ARCH: slc6_amd64_gcc493
    singularity: '6'
check_cv_CMSSW_7_6_7:
  extends: .check_cv_template
  variables:
    CMSSW_release: CMSSW_7_6_7
    SCRAM_ARCH: slc6_amd64_gcc493
    singularity: '6'
execute_cv_CMSSW_7_1_29:
  extends: .execute_cv_template
  variables:
    CMSSW_release: CMSSW_7_1_29
    SCRAM_ARCH: slc6_amd64_gcc481
    singularity: '6'
check_cv_CMSSW_7_1_29:
  extends: .check_cv_template
  variables:
    CMSSW_release: CMSSW_7_1_29
    SCRAM_ARCH: slc6_amd64_gcc481
    singularity: '6'
